version: 2
updates:
  # Enable version updates for master
  - package-ecosystem: "maven"
    # Look for the root pom
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps: "
    labels:
      - "dependencies"
    target-branch: "master"
    open-pull-requests-limit: 10
